### ISSUE TITLE
地址页面姓名顺序

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#10]
![Screenshot 2022-02-21 095701](https://user-images.githubusercontent.com/3207447/154989443-c75c3d34-6c35-4e8d-a161-dd26be2355ae.jpg)
Last Name 应该在后面 （Hu Fanghan 改为 Fanghan Hu）

**Comment by FanghanHu** [comment]
地址的格式为：
```
5750 Bintliff Dr #210
Houston, Texas, 77036
```

国家不写

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/155045589-02e28d2c-1e8b-4234-ae00-38f996e19eec.png)
已修改地址的排序方式

**Comment by FanghanHu** [comment]
地址顺序错了， 下面应该是 城市， 州， zipcode

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/155271412-197ab47d-2af1-4419-ab78-d128e1eefee9.png)
已调换顺序
