### ISSUE TITLE
前台用户界面修改

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#11]
![Screenshot 2022-02-21 100202](https://user-images.githubusercontent.com/3207447/154990969-c61e67a6-1bc7-4d0a-8dda-a809e584fef4.png)

将自我介绍去除， 然后修改一部分文本。
然后默认图标换一下：
![profile](https://user-images.githubusercontent.com/3207447/154991732-cab45948-d1fd-4f2f-b787-15af4cb3313a.png)
![man](https://user-images.githubusercontent.com/3207447/154991745-631efca1-b81e-4314-9e03-d26c467f8c91.png)

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/155046256-3c271d36-c5d7-4fdc-b7bb-7af4965befa3.png)
已经修改
