### ISSUE TITLE
后台发货页面的包裹信息换成可选

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#12]
![Screenshot 2022-02-21 101743](https://user-images.githubusercontent.com/3207447/154992858-b183c621-f71e-4ef1-af03-da9153fa9f78.jpg)

调整为可以选择在这个页面购买标签或者是添加其他渠道获得的追踪码

**Comment by chenqianglocaltiongit** [comment]
以增加相应功能
![image](https://user-images.githubusercontent.com/65063142/155283619-5b969e8d-a6b7-4cca-82d6-6d52b2c4423f.png)
