### ISSUE TITLE
产品说明页面无法上传图片

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#14]
![Screenshot 2022-02-21 111240](https://user-images.githubusercontent.com/3207447/155000816-0a399283-ad50-4a3e-8fb0-8ccf0c6103b2.jpg)
图片上传按钮打开的上传对话框不在最上层， 被商品设定页面挡住无法使用。

**Comment by chenqianglocaltiongit** [comment]
已修复
![image](https://user-images.githubusercontent.com/65063142/155137992-8025a1f1-0a93-4df3-957e-726492883e07.png)
