### ISSUE TITLE
商品邮寄选项设置

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#15]
![image](https://user-images.githubusercontent.com/3207447/155557849-8d5d7938-6dba-43dd-a07d-c030f3a37149.png)

商品后台设置应该是可以选择我们提供的邮寄方式，然后每种邮寄方式设定不同的价格， 请参考ebay的界面设定:

![image](https://user-images.githubusercontent.com/3207447/155559913-65981e8f-97c3-4412-8b2d-f6ea8281d5bf.png)

我们现在只需要支持 Flat Rate for all buyer 即可， 也就是我们自己手动设置每种邮寄方式的收费。

**Comment by FanghanHu** [comment]
文本修改： 
邮费 英文是： Shipping Fee
enable 的反义词应该为 disable

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/156114034-2968dcf9-c769-49f3-81d7-46034cab722a.png)
yichu已处理
