### ISSUE TITLE
文本修改： 选择图片

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#16]
![image](https://user-images.githubusercontent.com/3207447/155561188-974dcc34-f232-4234-b439-64b8d2c6b2b8.png)
choice 改为 select

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/155635078-75a2544b-e18c-44c5-b4ac-6bfb0d95acb9.png)
已修改
