### ISSUE TITLE
UI 修改：商城类别

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#18]
请参考这个网站：https://xcellparts.com/
![image](https://user-images.githubusercontent.com/3207447/155565157-77b0760e-71e7-4d12-bcf9-4385f70bbe5d.png)

一直显示的Navbar 内放一级菜单
下拉菜单内显示 二级菜单 和各个商品

**Comment by chenqianglocaltiongit** [comment]
商城分类ui确认
![image](https://user-images.githubusercontent.com/65063142/155646362-d25e3963-4872-40bc-8910-1b0c84101606.png)

**Comment by chenqianglocaltiongit** [comment]
实际展示效果
![image](https://user-images.githubusercontent.com/65063142/155664938-22c33d77-2ca0-4ad1-8821-1e3249a4b1df.png)
