### ISSUE TITLE
自动选择默认选项（商品页面， 购物车）

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#2]
打开商品页面时自动选择一个默认SKU， 打开购物车时自动选取所有物品
![Screenshot 2022-02-17 093521](https://user-images.githubusercontent.com/3207447/154518482-e6af23ba-fd6f-4af4-a8ea-5c948e807971.jpg)
![Screenshot 2022-02-17 094421](https://user-images.githubusercontent.com/3207447/154518486-59f934b8-ff0b-4764-b180-19b0d36ecd33.jpg)
。

**Comment by chenqianglocaltiongit** [comment]
已修改
