### ISSUE TITLE
文本修改： 付款结算

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#20]
![image](https://user-images.githubusercontent.com/3207447/155575332-8794df2a-e59c-4e17-b7ab-8e98f526ce2d.png)

参考ebay：
![image](https://user-images.githubusercontent.com/3207447/155575738-51640042-9344-4fc5-8bd3-a44df7473d5c.png)

改为：
Subtotal: 
Shipping: 
Tax:
Total:

**Comment by chenqianglocaltiongit** [comment]
文本已修改
![Uploading image.png…]()
