### ISSUE TITLE
前台和后台显示结账价格不同

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#21]
![image](https://user-images.githubusercontent.com/3207447/155577575-512d855c-0127-4f1b-8453-71e381d88701.png)
![image](https://user-images.githubusercontent.com/3207447/155577872-8ec44523-c6d6-4439-9927-e9a464559b60.png)

**Comment by chenqianglocaltiongit** [comment]
已处理
![image](https://user-images.githubusercontent.com/65063142/155632102-e3ad132b-62ed-4677-b9fe-0fe095fedd58.png)
![Uploading image.png…]()
