### ISSUE TITLE
文本修改： 维修预约

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#22]
![image](https://user-images.githubusercontent.com/3207447/156008913-a2599bf9-3768-4610-a1d9-84b85852289d.png)

英文为： Edit

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/156119899-a83e18dd-33ae-435e-b1e3-f64cfedb5c9c.png)
已修改
