### ISSUE TITLE
商品类别下拉菜单UI修改

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#26]
![ApplicationFrameHost_8KtqaFuHi9](https://user-images.githubusercontent.com/3207447/156040925-265887e8-f01d-4f80-ad46-8e64dccb35a1.gif)
[dropdown menu.zip](https://github.com/FanghanHu/lenwell-digital/files/8155874/dropdown.menu.zip)

**Comment by chenqianglocaltiongit** [comment]
![Uploading image.png…]()

**Comment by FanghanHu** [comment]
背景变暗

**Comment by chenqianglocaltiongit** [comment]
![Uploading image.png…]()
