### ISSUE TITLE
付款页面UI修改

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#28]
![settlement-page](https://user-images.githubusercontent.com/3207447/156056093-fed1ca2a-a33f-408a-b78b-ec0e603ce8ad.png)

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/156094497-356634a2-e910-4ea9-9f49-56f15678c88f.png)
已修改
