### ISSUE TITLE
商品细节页面， 邮寄方式无法删除。

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#35]
![chrome_qiqWF3iTKe](https://user-images.githubusercontent.com/3207447/158217528-7b65a066-4de6-41ff-95a8-b2103544d533.gif)

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162948561-cc46cf9a-b0e4-455a-9b23-8c19ffdba01d.png)
已修改
