### ISSUE TITLE
首页两个carousel 不需要自动翻页

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#36]
![image](https://user-images.githubusercontent.com/3207447/160860063-a72275f4-cbb2-435d-973e-4e7de3a9877a.png)
将下方的小按钮的高度加高， 颜色变深。

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162941103-4c61e3a8-96c8-4a12-8be1-07b58ca0d837.png)
已修改
