### ISSUE TITLE
产品细节页面的scrollbar样式

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#38]
![image](https://user-images.githubusercontent.com/3207447/160867053-e2b62de6-b00d-472b-82de-332ae96b25ee.png)
![image](https://user-images.githubusercontent.com/3207447/160867181-e56ec496-7ea2-45ec-9c5c-6a35cafc0983.png)
去掉轨道和按钮， 将滑动条改为暗灰色圆头细长条， 上下方增加方向按钮， 若已滚动到底， 则隐藏方向按钮

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162938953-e6c9fe0b-efd7-4f8a-8b28-a622045b9e2e.png)
已修改

**Comment by FanghanHu** [comment]
是不是 track 和 thumb 的设置做反了？ 整个scrollbar 都是黑的， 看不见现在滚动到哪里了。

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/164244710-eb49a14e-b91c-4b45-8bc0-c1e3e5ad027c.png)
已修改
