### ISSUE TITLE
将C端客户添加维修单的过程改为多页面对话过程

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#4]
将这个页面从类似于购买一个商品的形式更改为类似预约一个服务的界面：
![Screenshot 2022-02-17 100105](https://user-images.githubusercontent.com/3207447/154521649-d30348cf-d934-492e-a995-49dfe7e1f5d1.jpg)

请参考Apple 的维修预约界面：
![chrome_AIzOWHQTb2](https://user-images.githubusercontent.com/3207447/154521814-a985fdcf-a19c-4b59-981e-0a82d7a00d7c.gif)

预定维修分为以下几个部奏：

- 客户登录后才可以打开预约维修界面
- 选择机型
- 选择维修项目
- 添加备注
- 选择运送方式（邮寄，直接来实体店）
- 显示店铺地址, 维修订单跟进链接，服务条款， 以及说明接下来客户应该打如何包邮寄 还是 应该到店铺后告诉店员单号。

这个改动较为复杂， 请先给我一个设计草图。

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/155643996-677c0bb5-b9a6-4120-be16-ebc1c9d9b763.png)
![image](https://user-images.githubusercontent.com/65063142/155644088-b1e9f27d-5bd1-4937-a03e-463ad5c6263e.png)
![image](https://user-images.githubusercontent.com/65063142/155644167-b5eb6a4a-8e0d-4a4b-a9fc-3d79380f8d26.png)
![image](https://user-images.githubusercontent.com/65063142/155644240-dc0a0cc6-44b2-4d7f-812e-d9fa2e3cd669.png)
![image](https://user-images.githubusercontent.com/65063142/155644405-bfa85111-f406-4133-902b-5c83f1dd936a.png)
![image](https://user-images.githubusercontent.com/65063142/155644484-ca3732b9-4917-44d5-95bd-240e0c31ea08.png)
大概的设计流程与布局

**Comment by FanghanHu** [comment]
这个没问题， 就按照这个流程做吧
