### ISSUE TITLE
产品细节内星星数量显示不正常

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#40]
![image](https://user-images.githubusercontent.com/3207447/161561188-2d3f9718-c1b9-45ab-9e51-834beeca5404.png)

星星是 Stars， 括号内的文本显示应该为：5.0 Stars 或者 3.5 Stars

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162929409-1c1e31b4-51d9-45ed-9ab6-74cbf9fcfbb7.png)
已修改
