### ISSUE TITLE
Shopping Cart 无法使用

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#41]
![image](https://user-images.githubusercontent.com/3207447/162219263-abbf2cf6-92e9-4d00-9f94-453687bc313d.png)

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162952545-6f52666f-1254-452b-be87-74aecdfc33b2.png)
已修复
