### ISSUE TITLE
Avatar 上传后需要重新登录才会更新

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#47]
![image](https://user-images.githubusercontent.com/3207447/162236462-6f91dff5-da7d-49c3-ae5f-ea8d5517531a.png)

上传Avatar 后， profile 页面内显示的图片改变后， 右上角图标avatar不会跟着更新， 需要重新登录后才会改变,

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162923019-95afdd4c-4e92-43fb-9c00-c5faeffbccc4.png)
已修改
