### ISSUE TITLE
地址管理页面输入框顺序调整

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#48]
![image](https://user-images.githubusercontent.com/3207447/162237419-01b0c09e-97de-499c-a49c-eff1907ecb10.png)
依照美国使用习惯， 输入框顺序应该为：
First name, Last name, Phone number, Email, Address, City, State, Zip, Country.

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162921238-b9b61a76-c05f-4721-b9d4-24193b52ad5c.png)
已调整
