### ISSUE TITLE
类别内下拉菜单缺少背景暗化

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#49]
![image](https://user-images.githubusercontent.com/3207447/162240790-5e619933-edfa-4146-84a3-52e136865c91.png)
菜单未展开：
![image](https://user-images.githubusercontent.com/3207447/162241560-80035162-5fd9-47db-a317-3f29b80f50a7.png)
展开后背景变暗：
![image](https://user-images.githubusercontent.com/3207447/162241615-ef2bd77d-6da5-44ac-a8c6-8724e64356ae.png)

**Comment by FanghanHu** [comment]
我这边看阴影显示有问题， 从中间截断了，阴影应该覆盖整个页面， 将用户的注意力集中到下拉菜单上。
 然后不够黑， 是个白色的阴影， 需要突出的菜单是白色背景， 所以你覆盖其他部分的应该用黑的阴影。
<img width="594" alt="image" src="https://user-images.githubusercontent.com/3207447/163240836-95bac7b4-228c-449e-aada-da959af0966c.png">

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/164238782-ecab11f4-99b6-4c12-aff9-4caed53b180c.png)
颜色已修改
