### ISSUE TITLE
Catalog, Repair Service 页面上方的carousel 改为一张图片外加标题

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#50]
![image](https://user-images.githubusercontent.com/3207447/162243698-3142131d-9962-4dee-aa57-7d5c54a9b738.png)

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162912403-4fa05ffc-12e6-4820-95f3-84651e584b93.png)yi'xiu已修改

**Comment by FanghanHu** [comment]
能再加个text-shadow 改善一下比较亮的图片下的可读性吗？
text-shadow: 4px 4px 6px #404040
然后字号再大一点， 居中放就好。

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/164237642-8efa754e-eea9-4857-899f-ff78e730b212.png)
已修改
