### ISSUE TITLE
Repair Service 维修页面输入框标题颜色

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#51]
![image](https://user-images.githubusercontent.com/3207447/162245678-12cbbce6-cf14-4a34-9d6e-4409cc0285b4.png)
标题应该和上面的输入框一样使用黑色.

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/162902822-76603bc5-4c4f-4eef-ba30-843424c2b3cc.png)
tixi已修改
