### ISSUE TITLE
默认购买商品数量改为1

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#53]
![image](https://user-images.githubusercontent.com/3207447/162247370-23e44cf9-8cd5-4d38-9ea3-a6d0f25e2c3c.png)

**Comment by chenqianglocaltiongit** [comment]
已修改
![image](https://user-images.githubusercontent.com/65063142/162897338-1cf6c79f-485c-42f9-8972-55be5c300eba.png)
