### ISSUE TITLE
在线客服界面与使用方式

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#54]
![image](https://user-images.githubusercontent.com/3207447/162247663-8f7323aa-cad2-477c-b6a0-1618716abade.png)
这个界面右边这片空白的地方是做什么的？
左上角标题颜色和背景对比度太低了，看不清。
客服如何接收消息，如何回复客人？

**Comment by chenqianglocaltiongit** [comment]
右边白框不显示任何东西，消息有前天账号回
![微信截图_20220412143430](https://user-images.githubusercontent.com/65063142/162896404-e65f0492-63e0-4798-be25-65e304907529.png)
![微信截图_20220412143541](https://user-images.githubusercontent.com/65063142/162896408-041009d4-b391-477f-a79f-81c8973787ed.png)
复
