### ISSUE TITLE
Android 注册新用户界面， 密码没有隐藏

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#57]
![1bcc7e83ed520f24143cd5a25966792](https://user-images.githubusercontent.com/3207447/163833126-33a0b0fe-e041-4075-8800-9050c45ce548.jpg)

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/164613138-b49ec505-8817-4cf7-8ba1-30a9642c4f6f.png)
yi已处理
