### ISSUE TITLE
找回密码界面错误

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#66]
![4e85d7d1bcc5a3533e4f043e7b1bc11](https://user-images.githubusercontent.com/3207447/165546822-e53bc9d3-22f1-4346-9765-b26e8798f08f.jpg)
邮箱输入框消失， 找回密码的流程没有向用户解释清楚， 密码没有隐藏。

**Comment by chenqianglocaltiongit** [comment]
操作流程已简化
