### ISSUE TITLE
客服页面无法发送消息

### ISSUE THREAD

**Issue by FanghanHu** [FanghanHu/lenwell-digital#9]
![Screenshot 2022-02-18 174557](https://user-images.githubusercontent.com/3207447/154775499-9c30bd31-18b4-41db-804d-bc6015039ed0.jpg)

**Comment by chenqianglocaltiongit** [comment]
已修改，先可以发送客服消息

**Comment by FanghanHu** [comment]
请重新查看， 我这边依旧是同样的错误提示： Message can not be empty.

**Comment by chenqianglocaltiongit** [comment]
![image](https://user-images.githubusercontent.com/65063142/155283404-120125e3-cc0d-4d39-ae90-5315322456be.png)
已处理好了
